import {
  IResolvedTemplateTheme,
  ITemplateTheme,
  TResumeDesign,
  TResumeSection,
  TResumeTemplate,
} from './resume-theme.types';

/**
 * Static design tables for the resume renderer: section ordering, per-template
 * themes, palettes, fonts and density presets. Pure data — no rendering logic.
 */
export const DEFAULT_SECTION_ORDER: TResumeSection[] = [
  'summary',
  'experience',
  'skills',
  'education',
  'careerScopes',
];

export const THEMES: Record<TResumeTemplate, ITemplateTheme> = {
  modern: {
    accent: '#2563EB',
    accentSoft: '#DBEAFE',
    background: '#FFFFFF',
    headerBackground: '#172554',
    headerText: '#FFFFFF',
    text: '#172033',
    muted: '#64748B',
    layout: 'left-sidebar',
    radius: '8px',
    font: 'Arial, Helvetica, sans-serif',
  },
  classic: {
    accent: '#27272A',
    accentSoft: '#E4E4E7',
    background: '#FFFFFF',
    headerBackground: '#FFFFFF',
    headerText: '#18181B',
    text: '#27272A',
    muted: '#71717A',
    layout: 'single',
    radius: '0',
    font: "Georgia, 'Times New Roman', serif",
  },
  creative: {
    accent: '#7C3AED',
    accentSoft: '#EDE9FE',
    background: '#FFFFFF',
    headerBackground: '#5B21B6',
    headerText: '#FFFFFF',
    text: '#2E1065',
    muted: '#6B7280',
    layout: 'left-sidebar',
    radius: '12px',
    font: 'Arial, Helvetica, sans-serif',
  },
  minimalist: {
    accent: '#0284C7',
    accentSoft: '#E0F2FE',
    background: '#FFFFFF',
    headerBackground: '#FFFFFF',
    headerText: '#0F172A',
    text: '#1E293B',
    muted: '#64748B',
    layout: 'single',
    radius: '0',
    font: 'Arial, Helvetica, sans-serif',
  },
  timeline: {
    accent: '#4F46E5',
    accentSoft: '#E0E7FF',
    background: '#FFFFFF',
    headerBackground: '#4338CA',
    headerText: '#FFFFFF',
    text: '#1E1B4B',
    muted: '#6366F1',
    layout: 'single',
    radius: '10px',
    font: 'Arial, Helvetica, sans-serif',
  },
  bold: {
    accent: '#DC2626',
    accentSoft: '#FEE2E2',
    background: '#FFFFFF',
    headerBackground: '#18181B',
    headerText: '#FFFFFF',
    text: '#18181B',
    muted: '#71717A',
    layout: 'left-sidebar',
    radius: '2px',
    font: 'Arial Black, Arial, Helvetica, sans-serif',
  },
  compact: {
    accent: '#1D4ED8',
    accentSoft: '#DBEAFE',
    background: '#FFFFFF',
    headerBackground: '#1E40AF',
    headerText: '#FFFFFF',
    text: '#1E293B',
    muted: '#64748B',
    layout: 'two-column',
    radius: '4px',
    font: 'Arial, Helvetica, sans-serif',
  },
  elegant: {
    accent: '#A16207',
    accentSoft: '#FEF3C7',
    background: '#FFFBEB',
    headerBackground: '#FEF3C7',
    headerText: '#422006',
    text: '#422006',
    muted: '#78716C',
    layout: 'left-sidebar',
    radius: '10px',
    font: "Georgia, 'Times New Roman', serif",
  },
  colorful: {
    accent: '#0F766E',
    accentSoft: '#CCFBF1',
    background: '#FFFFFF',
    headerBackground: '#0F766E',
    headerText: '#FFFFFF',
    text: '#312E81',
    muted: '#6B7280',
    layout: 'left-sidebar',
    radius: '14px',
    font: 'Arial, Helvetica, sans-serif',
  },
  professional: {
    accent: '#0369A1',
    accentSoft: '#E0F2FE',
    background: '#FFFFFF',
    headerBackground: '#F1F5F9',
    headerText: '#0F172A',
    text: '#1E293B',
    muted: '#64748B',
    layout: 'left-sidebar',
    radius: '6px',
    font: 'Arial, Helvetica, sans-serif',
  },
  corporate: {
    accent: '#1D4ED8',
    accentSoft: '#DBEAFE',
    background: '#FFFFFF',
    headerBackground: '#1E3A5F',
    headerText: '#FFFFFF',
    text: '#1E293B',
    muted: '#64748B',
    layout: 'two-column',
    radius: '4px',
    font: 'Arial, Helvetica, sans-serif',
  },
  dark: {
    accent: '#58A6FF',
    accentSoft: '#1C2128',
    background: '#161B22',
    headerBackground: '#0D1117',
    headerText: '#E6EDF3',
    text: '#E6EDF3',
    muted: '#8B949E',
    layout: 'right-sidebar',
    radius: '6px',
    font: "'Courier New', Courier, monospace",
  },
  executive: {
    accent: '#B45309',
    accentSoft: '#FDE68A',
    background: '#FFFFFF',
    headerBackground: '#1C1917',
    headerText: '#F5F5F4',
    text: '#292524',
    muted: '#78716C',
    layout: 'right-sidebar',
    radius: '0',
    font: "Georgia, 'Times New Roman', serif",
  },
  tech: {
    accent: '#10B981',
    accentSoft: '#D1FAE5',
    background: '#FFFFFF',
    headerBackground: '#022C22',
    headerText: '#ECFDF5',
    text: '#1E293B',
    muted: '#64748B',
    layout: 'left-sidebar',
    radius: '4px',
    font: "'Courier New', Courier, monospace",
  },
  academic: {
    accent: '#155E75',
    accentSoft: '#CFFAFE',
    background: '#FFFFFF',
    headerBackground: '#FFFFFF',
    headerText: '#164E63',
    text: '#1E293B',
    muted: '#64748B',
    layout: 'single',
    radius: '0',
    font: "Georgia, 'Times New Roman', serif",
  },
  startup: {
    accent: '#EA580C',
    accentSoft: '#FFEDD5',
    background: '#FFFFFF',
    headerBackground: '#FFF7ED',
    headerText: '#7C2D12',
    text: '#431407',
    muted: '#78716C',
    layout: 'two-column',
    radius: '14px',
    font: "'Trebuchet MS', Verdana, sans-serif",
  },
  swiss: {
    accent: '#DC2626',
    accentSoft: '#FEE2E2',
    background: '#FFFFFF',
    headerBackground: '#FFFFFF',
    headerText: '#111827',
    text: '#111827',
    muted: '#6B7280',
    layout: 'single',
    radius: '0',
    font: 'Helvetica, Arial, sans-serif',
  },
  pastel: {
    accent: '#BE185D',
    accentSoft: '#FCE7F3',
    background: '#FFFFFF',
    headerBackground: '#FCE7F3',
    headerText: '#831843',
    text: '#4C1D3D',
    muted: '#71717A',
    layout: 'right-sidebar',
    radius: '14px',
    font: 'Verdana, Geneva, sans-serif',
  },
};

export const DESIGN_PALETTES: Record<
  TResumeDesign['palette'],
  {
    accent: string;
    accentSoft: string;
    background: string;
    header: string;
    headerText: string;
    text: string;
    muted: string;
  }
> = {
  ocean: {
    accent: '#0E7490',
    accentSoft: '#CFFAFE',
    background: '#F8FEFF',
    header: '#164E63',
    headerText: '#FFFFFF',
    text: '#153243',
    muted: '#527080',
  },
  cobalt: {
    accent: '#2563EB',
    accentSoft: '#DBEAFE',
    background: '#FFFFFF',
    header: '#1E3A8A',
    headerText: '#FFFFFF',
    text: '#172554',
    muted: '#64748B',
  },
  violet: {
    accent: '#7C3AED',
    accentSoft: '#EDE9FE',
    background: '#FEFCFF',
    header: '#4C1D95',
    headerText: '#FFFFFF',
    text: '#2E1065',
    muted: '#6B6480',
  },
  emerald: {
    accent: '#047857',
    accentSoft: '#D1FAE5',
    background: '#FBFFFD',
    header: '#064E3B',
    headerText: '#FFFFFF',
    text: '#143D32',
    muted: '#5D746D',
  },
  amber: {
    accent: '#B45309',
    accentSoft: '#FEF3C7',
    background: '#FFFCF5',
    header: '#78350F',
    headerText: '#FFFFFF',
    text: '#451A03',
    muted: '#78716C',
  },
  rose: {
    accent: '#BE123C',
    accentSoft: '#FFE4E6',
    background: '#FFFDFD',
    header: '#881337',
    headerText: '#FFFFFF',
    text: '#4C0519',
    muted: '#7B6870',
  },
  graphite: {
    accent: '#475569',
    accentSoft: '#E2E8F0',
    background: '#FFFFFF',
    header: '#1E293B',
    headerText: '#FFFFFF',
    text: '#1E293B',
    muted: '#64748B',
  },
  midnight: {
    accent: '#60A5FA',
    accentSoft: '#1E293B',
    background: '#0F172A',
    header: '#020617',
    headerText: '#F8FAFC',
    text: '#E2E8F0',
    muted: '#94A3B8',
  },
  sand: {
    accent: '#A16207',
    accentSoft: '#FEF3C7',
    background: '#FFFBEB',
    header: '#713F12',
    headerText: '#FFFFFF',
    text: '#422006',
    muted: '#78716C',
  },
};

export const DESIGN_FONTS: Record<TResumeDesign['typography'], string> = {
  sans: 'Arial, Helvetica, sans-serif',
  serif: "Georgia, 'Times New Roman', serif",
  geometric: "'Trebuchet MS', Arial, sans-serif",
  humanist: "'Segoe UI', Arial, sans-serif",
  mono: "'Courier New', Courier, monospace",
};

export const DESIGN_DENSITY: Record<
  TResumeDesign['density'],
  Pick<
    IResolvedTemplateTheme,
    | 'bodyFontSize'
    | 'lineHeight'
    | 'sidebarWidth'
    | 'headerPadding'
    | 'contentPadding'
    | 'avatarSize'
    | 'nameSize'
    | 'sectionGap'
    | 'experiencePadding'
  >
> = {
  compact: {
    bodyFontSize: 11.5,
    lineHeight: 1.35,
    sidebarWidth: 200,
    headerPadding: '24px 22px',
    contentPadding: '22px 26px',
    avatarSize: 72,
    nameSize: 22,
    sectionGap: 16,
    experiencePadding: '7px 9px',
  },
  balanced: {
    bodyFontSize: 13,
    lineHeight: 1.5,
    sidebarWidth: 225,
    headerPadding: '34px 28px',
    contentPadding: '30px 34px',
    avatarSize: 88,
    nameSize: 25,
    sectionGap: 24,
    experiencePadding: '10px 12px',
  },
  spacious: {
    bodyFontSize: 13.5,
    lineHeight: 1.65,
    sidebarWidth: 245,
    headerPadding: '40px 34px',
    contentPadding: '36px 42px',
    avatarSize: 96,
    nameSize: 28,
    sectionGap: 29,
    experiencePadding: '13px 15px',
  },
};

export const CUSTOM_ACCENT_PATTERN = /^#[0-9A-Fa-f]{6}$/;
