export const JOB_SERVICE = {
  NAME: 'JOB_SERVICE',
  ACTIONS: {
    FIND_ALL_JOBS: { cmd: 'findAllJobs' },
    SEARCH_JOBS: { cmd: 'searchJobs' },
    FIND_ONE_JOB: { cmd: 'findOneJob' },
    FIND_PUBLIC_JOB_SITEMAP: { cmd: 'findPublicJobSitemap' },
    EMPLOYEE_LIKES: { cmd: 'employeeLikes' },
    COMPANY_LIKES: { cmd: 'companyLikes' },
    UNMATCH: { cmd: 'unmatch' },
    ARE_USERS_MATCHED: { cmd: 'areUsersMatched' },
    FIND_CURRENT_EMPLOYEE_LIKED: { cmd: 'findCurrentEmployeeLiked' },
    FIND_CURRENT_COMPANY_LIKED: { cmd: 'findCurrentCompanyLiked' },
    FIND_CURRENT_EMPLOYEE_MATCHING: { cmd: 'findCurrentEmployeeMatching' },
    FIND_CURRENT_COMPANY_MATCHING: { cmd: 'findCurrentCompanyMatching' },
    FIND_CURRENT_EMPLOYEE_MATCHING_COUNT: {
      cmd: 'findCurrentEmployeeMatchingCount',
    },
    FIND_CURRENT_COMPANY_MATCHING_COUNT: {
      cmd: 'findCurrentCompanyMatchingCount',
    },
    MARK_EMPLOYEE_MATCHING_SEEN: { cmd: 'markEmployeeMatchingSeen' },
    MARK_COMPANY_MATCHING_SEEN: { cmd: 'markCompanyMatchingSeen' },
    GET_ANALYTICS: { cmd: 'getAnalytics' },
    AI_MATCH_EXPLANATION: { cmd: 'aiMatchExplanation' },
    AI_INTERVIEW_PREP: { cmd: 'aiInterviewPrep' },
    GET_AI_MATCH_PROFILES: { cmd: 'getAiMatchProfiles' },
    CREATE_INTERVIEW: { cmd: 'createInterview' },
    GET_INTERVIEWS_BY_EMPLOYEE: { cmd: 'getInterviewsByEmployee' },
    GET_INTERVIEWS_BY_COMPANY: { cmd: 'getInterviewsByCompany' },
    UPDATE_INTERVIEW_STATUS: { cmd: 'updateInterviewStatus' },
    APPLY_JOB: { cmd: 'applyJob' },
    GET_MY_APPLICATIONS: { cmd: 'getMyApplications' },
    GET_JOB_APPLICATIONS: { cmd: 'getJobApplications' },
    UPDATE_APPLICATION_STATUS: { cmd: 'updateApplicationStatus' },
    WITHDRAW_APPLICATION: { cmd: 'withdrawApplication' },
    BULK_UPDATE_APPLICATION_STATUS: { cmd: 'bulkUpdateApplicationStatus' },
    GET_JOB_PIPELINE: { cmd: 'getJobPipeline' },
    CREATE_APPLICATION_NOTE: { cmd: 'createApplicationNote' },
    LIST_APPLICATION_NOTES: { cmd: 'listApplicationNotes' },
    DELETE_APPLICATION_NOTE: { cmd: 'deleteApplicationNote' },
    LIST_APPLICATION_STATUS_HISTORY: {
      cmd: 'listApplicationStatusHistory',
    },
    LIST_SAVED_SEARCHES: { cmd: 'listSavedSearches' },
    CREATE_SAVED_SEARCH: { cmd: 'createSavedSearch' },
    UPDATE_SAVED_SEARCH: { cmd: 'updateSavedSearch' },
    DELETE_SAVED_SEARCH: { cmd: 'deleteSavedSearch' },
    PREVIEW_SAVED_SEARCH: { cmd: 'previewSavedSearch' },
    GET_EMPLOYER_ANALYTICS: { cmd: 'getEmployerAnalytics' },
  },
};
