export const JOB_SERVICE = {
  NAME: 'JOB_SERVICE',
  ACTIONS: {
    FIND_ALL_JOBS: { cmd: 'findAllJobs' },
    SEARCH_JOBS: { cmd: 'searchJobs' },
    FIND_ONE_JOB: { cmd: 'findOneJob' },
    EMPLOYEE_LIKES: { cmd: 'employeeLikes' },
    COMPANY_LIKES: { cmd: 'companyLikes' },
    FIND_CURRENT_EMPLOYEE_LIKED: { cmd: 'findCurrentEmployeeLiked' },
    FIND_CURRENT_COMPANY_LIKED: { cmd: 'findCurrentCompanyLiked' },
    FIND_CURRENT_EMPLOYEE_MATCHING: { cmd: 'findCurrentEmployeeMatching' },
    FIND_CURRENT_COMPANY_MATCHING: { cmd: 'findCurrentCompanyMatching' },
    FIND_CURRENT_EMPLOYEE_MATCHING_COUNT: {
      cmd: 'findCurrentEmployeeMatchingCount',
    },
    FIND_CURRENT_COMPANY_MATCHING_COUNT: {
      cmd: 'findCurrentCompanyMatchingCount',
    },
    GET_ANALYTICS: { cmd: 'getAnalytics' },
    AI_MATCH_EXPLANATION: { cmd: 'aiMatchExplanation' },
    AI_INTERVIEW_PREP: { cmd: 'aiInterviewPrep' },
    GET_AI_MATCH_PROFILES: { cmd: 'getAiMatchProfiles' },
    CREATE_INTERVIEW: { cmd: 'createInterview' },
    GET_INTERVIEWS_BY_EMPLOYEE: { cmd: 'getInterviewsByEmployee' },
    GET_INTERVIEWS_BY_COMPANY: { cmd: 'getInterviewsByCompany' },
    UPDATE_INTERVIEW_STATUS: { cmd: 'updateInterviewStatus' },
    APPLY_JOB: { cmd: 'applyJob' },
    GET_MY_APPLICATIONS: { cmd: 'getMyApplications' },
    GET_JOB_APPLICATIONS: { cmd: 'getJobApplications' },
    UPDATE_APPLICATION_STATUS: { cmd: 'updateApplicationStatus' },
    WITHDRAW_APPLICATION: { cmd: 'withdrawApplication' },
  },
};
