export const USER_SERVICE = {
  NAME: 'USER_SERVICE',
  ACTIONS: {
    FIND_ALL_EMPLOYEE: { cmd: 'findAllEmployee' },
    COUNT_ALL_EMPLOYEE: { cmd: 'countAllEmployee' },
    FIND_ONE_EMPLOYEE_BY_ID: { cmd: 'findOneEmployeeById' },
    SEARCH_EMPLOYEES: { cmd: 'searchEmployees' },
    UPLOAD_EMPLOYEE_AVATAR: { cmd: 'uploadEmployeeAvatar' },
    UPDATE_EMPLOYEE_INFO: { cmd: 'updateEmployeeInfo' },
    REMOVE_EMPLOYEE_AVATAR: { cmd: 'removeEmployeeAvatar' },
    UPLOAD_EMPLOYEE_RESUME: { cmd: 'uploadEmployeeResume' },
    REMOVE_EMPLOYEE_RESUME: { cmd: 'removeEmployeeResume' },
    UPLOAD_EMPLOYEE_COVER_LETTER: { cmd: 'uploadEmployeeCoverLetter' },
    REMOVE_EMPLOYEE_COVER_LETTER: { cmd: 'removeEmployeeCoverLetter' },
    REMOVE_EMPLOYEE_EXPERIENCE: { cmd: 'removeEmployeeExperience' },
    REMOVE_EMPLOYEE_EDUCATION: { cmd: 'removeEmployeeEducation' },

    FIND_ALL_COMPANY: { cmd: 'findAllCompany' },
    COUNT_ALL_COMPANY: { cmd: 'countAllCompany' },
    FIND_ONE_COMPANY_BY_ID: { cmd: 'findOneCompanyById' },
    UPLOAD_COMPANY_AVATAR: { cmd: 'uploadCompanyAvatar' },
    UPDATE_COMPANY_INFO: { cmd: 'updateCompanyInfo' },
    REMOVE_COMPANY_AVATAR: { cmd: 'removeCompanyAvatar' },
    UPLOAD_COMPANY_COVER: { cmd: 'uploadCompanyCover' },
    REMOVE_COMPANY_COVER: { cmd: 'removeCompanyCover' },
    UPLOAD_COMPANY_IMAGES: { cmd: 'uploadCompanyImage' },
    REMOVE_COMPANY_IMAGES: { cmd: 'removeCompanyImage' },
    REMOVE_OPEN_POSITION: { cmd: 'removeOpenPosition' },

    FIND_ALL: { cmd: 'findAll' },
    COUNT_ALL_USERS: { cmd: 'countAllUsers' },
    FIND_ONE_BY_ID: { cmd: 'findOneById' },
    FIND_ONE_BY_NAME: { cmd: 'findOneByName' },
    GET_CURRENT_USER: { cmd: 'getCurrentUser' },

    ADD_EMPLOYEE_TO_FAVORITE: { cmd: 'addEmployeeToFavorite' },
    REMOVE_EMPLOYEE_FROM_FAVORITE: { cmd: 'removeEmployeeFromFavorite' },
    ADD_COMPANY_TO_FAVORITE: { cmd: 'addCompanyToFavorite' },
    REMOVE_COMPANY_FROM_FAVORITE: { cmd: 'removeCompanyFromFavorite' },
    FIND_ALL_EMPLOYEE_FAVORITE: { cmd: 'findAllEmployeeFavorite' },
    FIND_ALL_COMPANY_FAVORITE: { cmd: 'findAllCompanyFavorite' },
    COUNT_COMPANY_FAVORITE: { cmd: 'countCompanyFavorite' },
    COUNT_EMPLOYEE_FAVORITE: { cmd: 'countEmployeeFavorite' },

    FIND_ALL_CAREER_SCOPES: { cmd: 'findAllCareerScopes' },
    UPDATE_PUSH_TOKEN: { cmd: 'updatePushNotificationToken' },
    CLEAR_CURRENT_USER_CACHE: { cmd: 'clearCurrentUserCache' },

    GET_EMPLOYEE_RECOMMENDATIONS: { cmd: 'getEmployeeRecommendations' },
    GET_COMPANY_RECOMMENDATIONS: { cmd: 'getCompanyRecommendations' },

    BLOCK_USER: { cmd: 'blockUser' },
    UNBLOCK_USER: { cmd: 'unblockUser' },
    LIST_BLOCKED_USERS: { cmd: 'listBlockedUsers' },
    GET_BLOCK_STATUS: { cmd: 'getBlockStatus' },
    GET_HIDDEN_PROFILE_IDS: { cmd: 'getHiddenProfileIds' },
    REPORT_USER: { cmd: 'reportUser' },
    REPORT_PROBLEM: { cmd: 'reportProblem' },

    ADMIN_OVERVIEW: { cmd: 'adminOverview' },
    ADMIN_LIST_USERS: { cmd: 'adminListUsers' },
    ADMIN_GET_USER: { cmd: 'adminGetUser' },
    ADMIN_UPDATE_USER_STATUS: { cmd: 'adminUpdateUserStatus' },
    ADMIN_LIST_REPORTS: { cmd: 'adminListReports' },
    ADMIN_UPDATE_REPORT_STATUS: { cmd: 'adminUpdateReportStatus' },
    ADMIN_LIST_AUDIT: { cmd: 'adminListAudit' },
  },
};
