export const HEALTH_DATABASE_TIMEOUT_MS = 2500;
export const HEALTH_MICROSERVICE_TIMEOUT_MS = 2500;
export const HEALTH_RPC_TIMEOUT_MS = 4000;
export const HEALTH_CACHE_PROBE_TTL_SECONDS = 5;
export const HEALTH_CACHE_PROBE_PREFIX = 'health';
